# idk if this is needed lol but let it be lol
import array
from re import search
import base64

# old method
"""
with open('this_is_a_bucket.txt', "r") as f:
    linez = f.readlines()
    # print(f.read())
    thefile = f.read()
    # print(f)
    print(thefile)
    
    print(linez)
    uscriptend_index = linez.index("this is line6\n")
    print(uscriptend_index)
    
    # insert pootis after the artificial line 6
    linez.insert(uscriptend_index + 1, 'pootis' + '\n')
"""


file = open("src/steam_addon_scanner.js")

# create an array of lines out of the input js file
linez = file.readlines()

# make the content of the file available as string because why not. wtf is wrong with python. wtf is this pornography
thefile = open("src/steam_addon_scanner.js").read()
# print(thefile)

# insert pootis after the artificial line 6 (test)
# linez.insert(uscriptend_index + 1, 'pootisded2' + '\n')

# convert css to base64
l3css = open("src/addon_scanner.css").read()
# encode css to ascii or whatever the fuckshit this it is
l3css_prep_enc = l3css.encode("ascii")
l3css_b64 = base64.b64encode(l3css_prep_enc)
# print(l3css_b64)


# find the index we need
# but first, let me take a selfie (check if what we check for exists lol)
if search('// ==/UserScript==', thefile):
    print('found // ==/UserScript==')
    uscriptend_index = linez.index("// ==/UserScript==\n")
else:
    print('// ==/UserScript== is not presented')



# insert css64
linez.insert(uscriptend_index + 1, '// css base64. Autogenerated.' + '\n' + 'window.super_css = "' + str(l3css_b64.decode("utf-8")) + '";')








# write js file
with open("steam_addon_scanner_r.js", "w") as txt_file:
    for line in linez:
        txt_file.write("".join(line))